import { Link, useNavigate } from 'react-router-dom';
import { ArrowRight, BrainCircuit, FileText, Sparkles, Target, ShieldCheck } from 'lucide-react';
import Layout from '../components/Layout';
import { getToken } from '../services/auth';

export default function Home() {
  const navigate = useNavigate();
  const token = getToken();

  return (
    <Layout>
      <div className="mx-auto max-w-7xl px-4 py-12 sm:px-6 lg:py-16 font-sans">
        {/* Hero Section */}
        <section className="reveal-up text-center max-w-3xl mx-auto py-8">
          <div className="mb-6 inline-flex items-center gap-2 rounded-full border border-inherit bg-current/10 px-4 py-1.5 text-xs font-bold font-mono">
            <Sparkles size={14} className="animate-pulse" />
            AI-POWERED PLACEMENT PREPARATION STUDIO
          </div>

          <h1 className="text-4xl font-black tracking-tight sm:text-5xl lg:text-6xl leading-tight text-glow-white">
            Master Technical Interviews <br className="hidden sm:inline" />
            <span className="underline decoration-current/30 underline-offset-8">
              With Pure AI Precision.
            </span>
          </h1>

          <p className="mt-6 text-base opacity-80 sm:text-lg leading-relaxed font-sans max-w-2xl mx-auto font-medium">
            Practice real-time AI mock interviews, optimize your resume for ATS screening, and build confident interview skills in a distraction-free environment.
          </p>

          <div className="mt-8 flex flex-col items-center justify-center gap-4 sm:flex-row">
            {token ? (
              <button
                onClick={() => navigate('/dashboard')}
                className="calm-button px-8 py-3.5 text-sm font-extrabold uppercase tracking-wider w-full sm:w-auto"
              >
                Go to Command Dashboard
                <ArrowRight size={16} className="ml-2" />
              </button>
            ) : (
              <>
                <Link
                  to="/register"
                  className="calm-button px-8 py-3.5 text-sm font-extrabold uppercase tracking-wider w-full sm:w-auto"
                >
                  Start Free Practice
                  <ArrowRight size={16} className="ml-2" />
                </Link>
                <Link
                  to="/login"
                  className="calm-button-outline px-8 py-3.5 text-sm font-bold uppercase tracking-wider w-full sm:w-auto"
                >
                  Sign In to Account
                </Link>
              </>
            )}
          </div>
        </section>

        {/* Feature Cards */}
        <section className="mt-16 grid gap-6 md:grid-cols-3">
          <div className="calm-card rounded-2xl p-6">
            <div className="flex h-10 w-10 items-center justify-center rounded-xl calm-button font-bold mb-4">
              <BrainCircuit size={20} />
            </div>
            <h3 className="text-lg font-bold mb-2 text-glow-subtle">Adaptive AI Mock Rounds</h3>
            <p className="text-sm opacity-75 leading-relaxed font-sans">
              Experience role-tailored technical questions generated by Gemini AI with instant diagnostic feedback.
            </p>
          </div>

          <div className="calm-card rounded-2xl p-6">
            <div className="flex h-10 w-10 items-center justify-center rounded-xl calm-button font-bold mb-4">
              <FileText size={20} />
            </div>
            <h3 className="text-lg font-bold mb-2 text-glow-subtle">ATS Resume Intelligence</h3>
            <p className="text-sm opacity-75 leading-relaxed font-sans">
              Upload your PDF/Word resume to get compatibility scores, missing keyword analysis, and section improvements.
            </p>
          </div>

          <div className="calm-card rounded-2xl p-6">
            <div className="flex h-10 w-10 items-center justify-center rounded-xl calm-button font-bold mb-4">
              <Target size={20} />
            </div>
            <h3 className="text-lg font-bold mb-2 text-glow-subtle">Company-Specific Tracks</h3>
            <p className="text-sm opacity-75 leading-relaxed font-sans">
              Prepare directly for target tech roles at companies like Google, Amazon, Microsoft, Meta, Flipkart, and TCS.
            </p>
          </div>
        </section>

        {/* Assurance Banner */}
        <section className="mt-16 calm-card rounded-2xl p-8 text-center max-w-4xl mx-auto">
          <div className="flex justify-center mb-3">
            <ShieldCheck size={28} />
          </div>
          <h2 className="text-xl font-bold mb-2 text-glow-white">Distraction-Free Environment</h2>
          <p className="text-sm opacity-80 max-w-xl mx-auto leading-relaxed font-sans">
            High contrast, crisp glowing typography, and instant Gemini feedback designed for ultimate focus and performance.
          </p>
        </section>
      </div>
    </Layout>
  );
}
